ome/omero-insight

Jenkinsfile
Jenkinsfile.merge
build.gradle
init-ci.gradle

These files will be used by devspace to merge all
open omero-insight PRs, push the resulting commit
to snoopycrimecop, and then build local artifacts.
see: https://github.com/openmicroscopy/devspace/pull/127

Jenkinsfiles for merge builds

---

build.gradle

Add a dependency for `javax.activation`. This is needed in order to be able to build with Java > 9.

Add javax.activation dep

---

build.gradle
buildSrc/build.gradle

Bump to m2 so that the version of executable is correctly set.
To test run either ``gradle packageApplicationDmg`` or ``gradle packageApplicationExe``
check that the generated distribution has the version ``5.5.0-SNAPSHOT``
a warning/error indicating that the version is "not correct" will be printed in the console but the distribution will be generated
There is no issue if a value like ``5.5.0`` is used
This PR also uses https://github.com/ome/omero-java-gateway instead of omero-blitz.

plugin bump

---

.travis.yml

Run ``gradle build on linux`` and ``gradle packageApplicationDmg`` on mac
* insight dmg will push to GH when a tag is set
* importer dmg will be built and pushed to GH when a tag is set
This has been tested using merge build of this PR and #22 https://github.com/jburel/omero-insight/releases/tag/v5.5.0-m14
* Check that travis is green
* Download the dmg and check that it can start

Travis: osx and linux build

---

src/main/java/org/openmicroscopy/shoola/util/ui/login/ServerEditor.java

Many people accidentaly enter the full OMERO.web URL as server name in Insight. This PR simply strips the `^https?://` part.
**Test:**
Add a new Server. Use `https://demo.openmicroscopy.org` as server name. You should then be able to simply connect to `demo.openmicroscopy.org`.

Silently strip http(s):// from the server name

---

src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java

Record error
Check that the application still runs 
cc @mtbc

Record error

---

src/main/java/org/openmicroscopy/shoola/env/LookupNames.java
src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java
src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ThumbnailLoader.java

Removes from Insight the special thumbnail handling for OMERO.server <5.4.8.

Deprecate SERVER_5_4_8_OR_LATER.

---

src/main/java/org/openmicroscopy/shoola/util/ui/treetable/OMETreeTable.java

This should fix the StackOverflowException you get when double clicking the comment field without an ROI being selected first, e. g. https://www.openmicroscopy.org/qa2/qa/feedback/27612/ 
I'm not quite sure yet, if this change has any other unwanted side effects.
Edit: Listing it for review now. Haven't noticed any side effects.

Prevent stackoverflow exception

---

CHANGELOG.md
build.gradle

Follows on from gh-54 by bumping GW _further_. Version bump for omero-insight and changelog are also included.

Bump to 5.5.3

---

.travis.yml

Attempt to correct https://github.com/ome/omero-insight/pull/61#issuecomment-518988457
> This is a random error. Travis needs to be restarted
cf:
```
Exception in thread "main" com.sun.javafx.tools.packager.PackagerException: Error: Bundler "DMG Installer" (dmg) failed to produce a bundle.
at com.sun.javafx.tools.packager.PackagerLib.generateNativeBundles(PackagerLib.java:354)
at com.sun.javafx.tools.packager.PackagerLib.generateDeploymentPackages(PackagerLib.java:319)
at com.sun.javafx.tools.packager.Main.main(Main.java:476)
```

Add travis_retry to dmg steps

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/ImagesImporter.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/TagsLoader.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponentI.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/LightFileImportComponent.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/Importer.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterComponent.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUI.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElement.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElementDetailed.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElementLight.java

Fixes the importer UI freeze when importing many images and enable the cancel, retry, submit buttons again. Together with https://github.com/ome/omero-gateway-java/pull/16 this should fix the issue https://github.com/ome/omero-insight/issues/57 .
**TEST**
Import > 4000 images on Windows. The issue affected all OS, but on Windows it was especially bad.
Should also be tested with just a couple of images, including multi-file images (eg. *.dv + *.log) to check if the 'normal' importer UI still works as expected.

Import ui fixes

---

src/main/java/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerModel.java

Bugfix for: https://www.openmicroscopy.org/qa2/qa/feedback/27791/ 
The 'cut' already happenend when then 'cut and paste' action is performed, so it tried to delete a link which didn't exist any longer. The logic/sequence of these actions must have changed at some point in the past.
Cut and paste a few images in Insight from one dataset to another.

Bugfix: Cut and paste

---

src/main/java/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerModel.java
src/main/java/org/openmicroscopy/shoola/util/ui/omeeditpane/OMEWikiConstants.java

Unify with CLI, figure the way the link to the original image is added to the description of the projected image
UI will now handle both case ``Image ID:<space>ID`` and ``Image ID:ID``
To test: (new image)
* Open an image with more than one z
* project the image
* Open the projected image
* A link to the original image should be available i.e. ``Image:ID``. 
* Double click to open the image. Close the viewer
* Modify the description by adding a space i.e. ``Image:<space>ID``
* Check that it is still highlighted in blue.
* Double click to open the image.
To test: (projection done previously) (user-1, 92215)
*  Open the projected image
* A link to the original image should be available i.e. ``Image ID: <space>ID``. 
* Modify the description by removing the a space i.e. ``Image ID:ID``
* …

Hyperlink in description

---

src/main/java/org/openmicroscopy/shoola/env/data/login/LoginServiceImpl.java

If you connect with current Insight 5.5.6 to for example merge-ci you get an error message like this:
It says Insight 5.5.4 because it gets the version of the java-gateway. This PR simply fixes the error message, so that it correctly states the version of Insight not the gateway one. Also removes the "Please download..." sentence, as we can't automatically determine any more which Insight version will be compatible with which server version.
See also https://forum.image.sc/t/omero-python-3-5-6-milestone-for-upgrade-testing/32120/5

Fix version error message

---

src/main/java/org/openmicroscopy/shoola/agents/util/ui/MovieExportDialog.java

Show a generic grey button if channel uses lookup table.
Fixes https://github.com/ome/omero-insight/issues/85
Test: On a multi-Z/T image set one or more channels to a lookup table. Open the "Movie Export" dialog.

Handle LUTs in MovieExportDialog

---

src/main/java/org/openmicroscopy/shoola/util/ui/login/ServerEditor.java

Just fixes two small issues with the server editor @pwalczysko noticed while adjusting the docs https://github.com/ome/omero-guide-upload/pull/3 .
- Now it's only possible to select a single entry in the server list (multi selection doesn't really make sense here).
- And you can select and delete the first server in the list.
Not a blocker for the current Insight release.

Fix two minor issues in ServerEditor

---

src/config/dataBrowser.xml

Folder was renamed to ``databrowser`` see https://github.com/ome/omero-insight/tree/47e40da08b9cff563df9894bc5490c15b545b17a/src/main/resources/images/agents/databrowser
but the value was not updated in the configuration file.
See https://github.com/ome/omero-insight/issues/55
cc @dominikl

fix missing icons

---

src/main/java/org/openmicroscopy/shoola/env/ui/TaskBarManager.java

Fix issue preventing to open images using B-F when using the imagej plugin
To test:
* Download the ``omero_ij`` jar
* connect to a server with ws enable e.g. workshop or outreach
* Open an image in ImageJ
* The image should open 
cc @pwalczysko @dominikl

IJ plugin open image when using websocket

---

src/main/java/org/openmicroscopy/shoola/env/ui/TaskBarManager.java

select the crop option if large image
to test: 
* Open a small image in Fiji, the crop option should not be selected
* Open a large image (image requiring pyramid), the crop option should be selected
cc @dominikl

Fiji: Crop option

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/chooser/FileSelectionTable.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java
src/main/java/org/openmicroscopy/shoola/env/data/model/ImportableFile.java

Attempt to fix https://github.com/ome/omero-insight/issues/94
Check the scenarii described in the issue,
If a user creates a new dataset, the hierarchy will be reloaded at the end of the import similar to what we do for "new from folder".
This means that if the user tries to import in the dataset (to be) "created", another dataset with the same name will be created. Similar to what happen with "new from folder"
This is the less intrusive change I could see
I also notice a space missing in the tooltip of a control
cc @dominikl

Import in wrong dataset

---

src/main/java/org/openmicroscopy/shoola/agents/metadata/editor/EditorControl.java
src/main/java/org/openmicroscopy/shoola/util/filter/file/CSVFilter.java
src/main/java/org/openmicroscopy/shoola/util/filter/file/ExcelFilter.java
src/main/java/org/openmicroscopy/shoola/util/filter/file/OpenDocumentFilter.java
src/main/java/org/openmicroscopy/shoola/util/filter/file/WordFilter.java

Add `csv` to the available file filters for the file attachment dialog. On that occassion also added the various "new" excel and word extensions and a filter for OpenDocument formats.
See: https://github.com/ome/omero-insight/issues/117

File filter

---

buildSrc/src/main/groovy/org/openmicroscopy/DistributePlugin.groovy

This fixes the issue described in https://github.com/ome/omero-insight/issues/25
To test locally
* run ``gradle build``
* unzip OMERO.importer.zip
* run ``bin/omero-importer``
or download the OMERO.importer from daily build and unzip

Bin importer

---

src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java

Fixes a bug in the script upload functionality. The bug prevented scripts from being recognized as already existing on the server, so the uploadScript call failed. See https://github.com/ome/omero-insight/issues/132 .
**Test**: Check the workflow mentioned in the issue now works.

Fix bug in script upload

---

src/main/java/org/openmicroscopy/shoola/agents/util/dnd/DnDTree.java

Removes the `canLink` method, which only checks if the dragged object belongs to the logged in user, and if it doesn't prevents the DnD action. I wonder why this method was there, because one doesn't necessarily have to be the owner of the object in order to be allowed to move it (see https://github.com/ome/omero-insight/issues/131 ).
**Test**: Check the scenario mentioned in the above issue now works.

Remove canLink method

---

src/main/java/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java

Just a tiny PR which changes the error message, as suggest by @jburel in https://github.com/ome/omero-insight/pull/133#issuecomment-625108884 .

Just change error message

---

src/main/java/org/openmicroscopy/shoola/env/data/model/FileObject.java

* Keep the title of the image plus.
This will keep the name of the channel in the final image name 
see https://github.com/ome/omero-insight/issues/48
cc @dominikl @pwalczysko

Fiji import image

---

src/main/java/org/openmicroscopy/shoola/env/ui/SplashScreenManager.java
src/main/java/org/openmicroscopy/shoola/env/ui/TaskBarManager.java
src/main/java/org/openmicroscopy/shoola/env/ui/login/ScreenLogin.java
src/main/java/org/openmicroscopy/shoola/env/ui/login/ScreenLoginDialog.java
src/main/java/org/openmicroscopy/shoola/env/ui/login/ScreenLogo.java
src/main/java/org/openmicroscopy/shoola/env/ui/login/ServerDialog.java
src/main/java/org/openmicroscopy/shoola/env/ui/login/ServerEditor.java
src/main/java/org/openmicroscopy/shoola/util/ui/login/ScreenLogin.java
src/main/java/org/openmicroscopy/shoola/util/ui/login/ServerEditor.java

See Gateway PR https://github.com/ome/omero-gateway-java/pull/34 , respectively issue https://github.com/ome/omero-gateway-java/issues/33 .
**Test**
Check that 'normal' login (hostname) and websocket login still works.
Check that you get a sensible error message if you try something like 'smb://someserver.org' .

Provide error message if unsupported protocol was used

---

src/main/java/org/openmicroscopy/shoola/env/data/model/FileObject.java

Returns `/` (or `\\` on windows) as folder name, if an image from a filesystem root directory is imported.
Fixes https://github.com/ome/omero-insight/issues/49 . Without PR, if you choose "Dataset from folder" in the import dialog: Image goes to Orphaned Images, if no Project is selected (crash if a project is selected). With PR: A dataset with name `/` (`\\` respectively) is created for the image.

Return root folder 'name' instead of empty string

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
src/main/java/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java

This fixes the problem described in https://github.com/ome/omero-insight/issues/148
@dominikl, you introduced the ``hasParent`` check back in 2018 but I cannot remember the rationale behind it

Import project

---

src/main/java/org/openmicroscopy/shoola/env/LookupNames.java
src/test/java/org/openmicroscopy/shoola/env/LookupNamesTest.java

The `USER_MDE_PATH` LookupName conflicted with the `USER_HOME_OMERO` one, which caused issues https://github.com/ome/omero-insight/issues/154 and https://github.com/ome/omero-insight/issues/153.
**Test**: 
See travis builds of last two commits to check that the units test works. 
Check that Insight still works as expected.
And check that Insight now picks up the correct location for its files again, e.g. the log file, see https://github.com/ome/omero-insight/issues/153 .

Fix bug; Lookupname for omero home dir was overwritten

---

build.gradle

Bumps to current version of gateway.

Bump to Java Gateway 5.6.5.

---

build.gradle

This commit follows the v5.5.14 tag now pushed to my fork: https://github.com/mtbc/omero-insight/releases/tag/v5.5.14.

Ready SNAPSHOT version for next release.

---

.github/workflows/gradle.yml
README.md

This PR 
* Windows: caps the java 8 version to ``8.0.275``, the version installed is now ``8.0.282`` and it no longer contains the ``javapackager`` that we use to build the ``.exe`` and ``.msi``. 
* Mac: ``brew cask`` has been removed and we now need to use ``brew install --cask``. Unfortunately the cask ``zulu8`` is no longer available. ``adoptopenjdk 8.0.275`` allows us to build the dmg.
The changes in this PR were used to build https://github.com/jburel/omero-insight/releases/tag/v5.5.15 see
https://github.com/jburel/omero-insight/actions/runs/530995148

Fix build artifacts

---

src/main/java/org/openmicroscopy/shoola/agents/util/ui/ScriptingDialog.java

Only pop up the dialog when the component is visable. Fixes https://github.com/ome/omero-insight/issues/189 . 
**Test**:
Code review only, don't know how to reproduce the issue, must be very intermittent.

Prevent potential IllegalComponentStateException

---

src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ThumbnailLoader.java

Catch all exceptions and use the error icon as thumbnails. Should fix https://github.com/ome/omero-insight/issues/192 (although I don't know why the Image's Pixeldata was `null` in that case).

Also catch NPEs in ThumbnailLoader

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java
src/main/java/org/openmicroscopy/shoola/util/ui/ClosableTabbedPane.java
src/main/java/org/openmicroscopy/shoola/util/ui/ClosableTabbedPaneUI.java

Prevent to close the ImportDialog tab. Fixes https://github.com/ome/omero-insight/issues/181 .
**Test**:
Right click on the "Select data to import" tab. Without the fix the "Close, Close All, etc." dialog will show up. If you close the tab via this dialog, close the importer dialog and open it again, it'll crash with the IllegalComponentStateException. With the fix you shouldn't have the possibility to close this tab.

Importdialog closeable

---

src/main/java/org/openmicroscopy/shoola/Main.java
src/main/java/org/openmicroscopy/shoola/env/Container.java
src/main/java/org/openmicroscopy/shoola/env/config/Registry.java
src/main/java/org/openmicroscopy/shoola/env/config/RegistryImpl.java
src/main/java/org/openmicroscopy/shoola/env/data/login/UserCredentials.java
src/main/java/org/openmicroscopy/shoola/env/ui/login/ScreenLogin.java
src/test/java/org/openmicroscopy/shoola/env/config/NullRegistry.java

Allows to pass through command line arguments to `omero.client`, e.g. `--Ice.HTTPProxyHost=PROXY --Ice.HTTPProxyPort=PORT`. Fixes https://github.com/ome/omero-insight/issues/190 . I'm still not sure how to pass through an `ICE_CONFIG` environment variable. But afaik this shouldn't be necessary as you can just use the command line arguments with this PR.
**Test**:
To check if the arguments are taken into account just use something like `--Ice.HTTPProxyHost=1.2.3.4` and you shouldn't be able to connect. Remove it again and you can connect again.

Pass through commandline arguments

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java

Avoid potential NPEs like https://github.com/ome/omero-insight/issues/180 in LocationDialog and ImportDialog.
**Test**:
I don't know how to replicate the NPE, but maybe just check that the Import workflow still works as expected.

Avoid potential NPEs

---

src/main/java/org/openmicroscopy/shoola/env/ui/TaskBarManager.java
src/main/java/org/openmicroscopy/shoola/env/ui/login/ScreenLoginDialog.java

This PR fixes a bug introduced by #197.
I noticed it after merging the PR
To test:
* Start OMERO.insight
* Go to ``File > switch user...``
* A dialog pops up
* Enter credentials and click login
cc @dominikl

fix npe when switching user

---

src/config/container.xml
src/config/containerImporter.xml
src/main/java/org/openmicroscopy/shoola/env/LookupNames.java
src/main/java/org/openmicroscopy/shoola/env/data/login/UserCredentials.java
src/main/java/org/openmicroscopy/shoola/env/ui/login/ScreenLogin.java

This should properly fix https://github.com/ome/omero-insight/issues/224 .
Test: Use 'pwtest' user with password ' test' (leading space!) and check the logs that the first login attempt works.

Escape ice special characters for login

---

src/config/container.xml
src/config/containerImporter.xml

For easier use of the OMERO.mde also for users who download the OMERO.insight as an `exe` . Default location for a `mdeConfiguration` file is the local user omero directory.

MDE enabled in the standard configuration of importer

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/ImporterAgent.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java
src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java

enables use of OMERO.importer with read-only server for metadata annotations with OMERO.mde.
Could be useful to assist the user with IDR submissions or to export to other metadata and data formats using OMERO.mde.

enable use of OMERO.importer with read-only server

---

src/main/java/org/openmicroscopy/shoola/env/LookupNames.java
src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java
src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java
src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ThumbnailLoader.java

Check that you can view the thumbnail when connecting to IDR
The functionality should remain the same for other server
Problem noticed while testing a workflow for the upcoming course
cc @pwalczysko

Load thumbnails when read-only

---

src/main/java/org/openmicroscopy/shoola/util/ui/graphutils/HistogramPlot.java

Don't throw Exception if there's no data to show, simply show empy histogram panel.
Fixes https://github.com/ome/omero-insight/issues/246 .
Replicate the issue: Open image with an ROI. Open ROI tool. Go to "Graph Pane". Select ROI. This should show the histogram. Then de-activate the channels in the Image viewer. Crash with IllegalArgumentException .
With the PR this should not crash, but just show an empy histogram, if the channels are deactivated.

Don't throw Exception if there's no data to show

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java

Attempt to fix https://github.com/ome/omero-insight/issues/210 . 
The error from the issue is typical if UI components have been removed from outside the Swing thread. In this code block a lot of UI updates, additions and removal of components is happening and it might be called asynchronosly. I suspect this could be the cause of the issue. Putting it into the Swing thread hopefully will fix the problem.
**Test**: Just test if this PR causes any issues for importing images. Test some imports, imports with just a few images, and imports with 2000+ images.

Move UI update code in Swing thread

---

src/main/java/org/openmicroscopy/shoola/env/ui/login/ServerEditor.java

Wee bugfix for https://github.com/ome/omero-insight/issues/256 .
Replicate issue: Click on the spanner to select server. Use CTRL click to deselect the current server. Click on the pencil to edit the hostname. Click ok. -> Crash
With this PR: If the server is deselected, the pencil icon will be deactivated.

Fix potential ArrayIndexOutOfBoundsException

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/MetaDataDialog.java

fix of QA 30579 (see #258): handle/catch empty file selection

handle empty file selection

---

src/main/java/org/openmicroscopy/shoola/util/ui/filechooser/GenericFileChooser.java

This should fix issue with file path.
see https://www.openmicroscopy.org/qa2/qa/feedback/30780/ and https://github.com/ome/omero-insight/issues/237
cc @dominikl

use toURI method to handle

---

src/main/java/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerWin.java

I don't know how to replicate https://github.com/ome/omero-insight/issues/274 but this PR should prevent it.

Make sure component is showing

---

src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java

Do not show the groups if a session key is used to connect
To test:
* Connect using username and password using a user in multiple groups. Check that the user can access the groups via the UI.
* Connect using a session key. Check that the user cannot access the other groups.

Hide groups if session key is used to connect

---

src/main/java/org/openmicroscopy/shoola/util/ui/filechooser/CustomizedFileChooser.java

Workaround for https://github.com/ome/omero-insight/issues/271 . This "File Format" dropdown is part of Java's builtin JFileChooser, so I can't remove it. This PR is a proposed workaround which simply disables it in case it's empty.
Test: Make sure it's still enabled when it should be (e.g. attach a file), and that it is disabled when it is empty (e.g. download an image).

Disable file format combobox

---

src/config/container.xml
src/config/containerImporter.xml
src/main/java/org/openmicroscopy/shoola/Main.java
src/main/java/org/openmicroscopy/shoola/agents/dataBrowser/view/DataBrowserWellToolBar.java
src/main/java/org/openmicroscopy/shoola/agents/dataBrowser/view/QuickSearch.java
src/main/java/org/openmicroscopy/shoola/agents/dataBrowser/view/SearchComponent.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElement.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElementLight.java
src/main/java/org/openmicroscopy/shoola/agents/imviewer/view/ToolBar.java
src/main/java/org/openmicroscopy/shoola/agents/metadata/editor/ToolBar.java
src/main/java/org/openmicroscopy/shoola/agents/metadata/util/AnalysisResultsItem.java
src/main/java/org/openmicroscopy/shoola/agents/treeviewer/view/ToolBar.java
src/main/java/org/openmicroscopy/shoola/env/data/util/StatusLabel.java
src/main/java/org/openmicroscopy/shoola/env/ui/ActivityComponent.java
src/main/java/org/openmicroscopy/shoola/util/CheckThreadViolationRepaintManager.java
src/main/java/org/openmicroscopy/shoola/util/ui/DummyPanel.java
src/main/java/org/openmicroscopy/shoola/util/ui/FileTableNode.java
src/main/java/org/openmicroscopy/shoola/util/ui/MessengerDialog.java

Another attempt to fix https://github.com/ome/omero-insight/issues/210 .
Used the `CheckThreadViolationRepaintManager` mentioned in https://stackoverflow.com/questions/3153574/how-to-detect-swing-thread-policy-violations to detect more code in the import context which triggers UI updates outside the Swing thread. Moved these parts into `SwingUtilities.invokeLater()` calls. 
**Testing**: The exceptions of issue 210 are random and not reproducable. But what needs testing is that the import workflows still work.
/cc @jburel

Issue 210: javax.swing.JComponent: ArrayIndexOutOfBoundsException

---

src/main/java/org/openmicroscopy/shoola/agents/treeviewer/view/ToolBar.java

Fixes issue https://github.com/ome/omero-insight/issues/313 . Tbh, I don't know how these errors happen, because the component must be visible in order for the user to click on it. But at least this will prevent the exception.

Fix issue 313

---

src/main/java/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerComponent.java

Just removes the call to load annotations for ROIs (we don't do anything with them anyway).
Should fix https://github.com/ome/omero-insight/issues/308 .

Don't load annotations for ROIs

---

src/main/java/org/openmicroscopy/shoola/agents/measurement/view/MeasurementViewerModel.java
src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java
src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java
src/main/java/org/openmicroscopy/shoola/env/data/OmeroDataService.java
src/main/java/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java
src/main/java/org/openmicroscopy/shoola/env/data/OmeroImageService.java
src/main/java/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java
src/main/java/org/openmicroscopy/shoola/env/data/views/calls/HistogramLoader.java
src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ROICountLoader.java
src/test/java/org/openmicroscopy/shoola/env/data/NullOmeroPojoService.java
src/test/java/org/openmicroscopy/shoola/env/data/NullRenderingService.java

Should fix most cases which trigger https://github.com/ome/omero-insight/issues/99 . This PR moves some Java Gateway calls into the OMEROGateway, because there connection issues can be dealt with by trying to reconnect.
Test: Open Insight, login, browse to a dataset with some images, click on one image. Disconnect from the network. Click on another image. Without the PR: Crash with connection exception. With the PR: Reconnection dialog will pop up. Connect to the network again. After a few seconds Insight should have recovered.
~~Note: I made the OMEROGateway class public for convenience,  otherwise I'd have to add another few delegation methods to the OMERODataservice class etc.~~

Move gateway calls to OMEROGateway

---

src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java

Companion to https://github.com/ome/omero-common/pull/38
Similarly to the logic retrieving the maximum plane width/height from the server, this adds another post-connection step to retrieve the value of the server-side `omero.qa.feedback` property. If defined, it sets the `LookupNames.TOKEN_URL` and `LookupNames.PROCESSING_URL` entries which are used for sending feedback (comments and failed uploads) to the QA server. If the calls fails e.g. with a `SecurityViolation`, the current behavior is unchanged and the default values set in `container.xml` should be used.
Testing should happen in different client/server scenarios:
- OMERO.insight with this PR included against OMERO.server without https://github.com/ome/omero-common/pull/38:
* if logged in as a normal user, the ConfigService call …

Add logic to retrieve omero.qa.feedback property server-side

---

src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java

Similar to d17677fa6 this avoids printing the entire server stack trace to the log file is the client is talking to an older server where the property is not exposed client-side.

DataServicesFactory: only log server exception class and message

---

src/main/java/org/openmicroscopy/shoola/env/config/Parser.java
src/main/java/org/openmicroscopy/shoola/env/config/RegistryFactory.java
src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java
src/main/java/org/openmicroscopy/shoola/env/init/ContainerConfigInit.java

add ability to reset the value of specified keys in registry
To test the proposed changed.
* Connect to a server with ``omero.qa.feedback`` configured.
* Select Switch user in menu and connect to another server without configuration
* Check that the qa url has changed to the value defined in ``container.xml``
cc @sbesson

Reset key in registry

---

src/main/java/org/openmicroscopy/shoola/env/data/AdminServiceImpl.java
src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java
src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java
src/main/java/org/openmicroscopy/shoola/env/ui/login/ScreenLogin.java

Remove the calls to joinSession, see https://github.com/ome/omero-gateway-java/pull/63 .

Remove joinSession

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/chooser/ImportDialog.java

This PR handles the attempt to import with invalid characters in the path.
The files will no be added to the list of files to import

check if the path is valid

---

build.gradle

The work on the upstream ome-* components to declare logback as optional dependencies (following the SLF4J best practice recommendations) has exposed the fact that omero-insight currently has a direct dependency on this logging implementation.
See https://github.com/ome/ome-metakit/pull/11#issuecomment-1386743130

Declare logback-classic as explicit dependency

---

src/main/java/org/openmicroscopy/shoola/agents/treeviewer/view/ToolBar.java

Fixes issue https://github.com/ome/omero-insight/issues/313 .
The problem is the first time you click on the scripts button, it replaces the script button with a spinner button while loading the available scripts from the server. The script button might not be back in time for the menu to be attached on.
**Test**:
- Replicate the issue with Insight relese version: Start up Insight, click on the "scripts" button. Very likely crash.
- With this PR: No crash. ~~But scripts menu will be shown slightly off to the left of the button on the first click as it is "attached" to the toolbar itself in that case.~~ Not any longer due to @jburel 's adjustment 👍

Show script menu on toolbar

---

.github/workflows/gradle.yml

Using the Gradle action installed the desired version of gradle preventing the failure. see https://github.com/ome/omero-insight/actions/runs/4202376704/jobs/7353445683
TODO: review other repositories
Check that the build is green

use gradle action

---

src/main/java/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java
src/main/java/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java

The easiest way to test this PR
is to return ``null`` instead of the ``pojo`` at https://github.com/ome/omero-insight/blob/master/src/main/java/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java#L346 (now line 348)
see #367

handle Null object when attempting to create an object

---

FAQ.md
src/main/java/org/openmicroscopy/shoola/Main.java
src/main/java/org/openmicroscopy/shoola/env/Container.java

Fixes https://github.com/ome/omero-insight/issues/363 .
You can start Insight with a positional argument pointing to the container xml (e.g. container.xml for the "normal" Insight, containerImport.xml for the Importer). In the OSX build this argument is set by OMERO.insight.cfg:
```
[ArgOptions]
container.xml
```
Without this PR the container xml has to be in the config directory within the bundle. With this PR you can point to any location. If the argument contains at least one path character it is assumed it specifies a file outside the bundle, if it doesn't (i.e. it's only a file name) it's assumed that it specifies a file within config directory of the bundle.
The PR also removes the code to enable the DebugRepaintManager, as it's actually not used any more.

Enable pointing to external container xml

---

src/main/java/org/openmicroscopy/shoola/agents/dataBrowser/view/SearchResultTable.java

see https://github.com/ome/omero-insight/issues/361
The View button displayed in the table will open the image in Fiji when used in the plugin
To test: 
* search for an image e.g. using id
* in the result table. Click on the ``View`` button.
* The image should open in Fiji

open image in imageJ when using as IJ plugin

---

.mailmap

This PR adds a top-level mapping file allowing to normalize commits from the same contributor and associate all commits to a canonical "First Name Last Name <email>" author line.
The following rules are used for the construction of the .mailmap file:
- for all contributors who are employees of the University or Dundee, Glencoe Software, the `@dundee.ac.uk`,  or `@glencoesoftware.com` email address is used as the canonical email address
- for all contributors with an executed CLA, the real name and email address sent via the CLA is used as the canonical address
- for all contributors, the name used in https://www.openmicroscopy.org/teams/ or https://www.openmicroscopy.org/contributors/ is used as the canonical real name.
The .mailmap is constructed according to the official …

Add top-level Git mailmap to normalize commit author variants

---

CHANGELOG.md

Record PR to consider for next release

Changelog for 5.8.2 

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/FileImportComponent.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/util/LightFileImportComponent.java
src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java
src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java
src/main/java/org/openmicroscopy/shoola/env/data/OmeroImageService.java
src/main/java/org/openmicroscopy/shoola/env/data/OmeroImageServiceImpl.java
src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ImagesImporter.java
src/test/java/org/openmicroscopy/shoola/env/data/NullRenderingService.java

This PR replaces #354
Run an import of one or multiple filesets and watch the creation/deletion of HandleTie servants server-side e.g. using ``tail -F Blitz-0.log  | grep HandleTie.``
All the handles should now be closed and the service closed.
Thumbnails are no longer loaded
To test:
* regular import of single files
* regular import of directories (1-10 & >50 to test the lightfileimport)
* import of broken files (failing server-side)
* import of HCS data
* import of some images which take longer to process on the server side and closing insight before the server side import is finished.

Close all HandleTie servants created during import

---

src/main/java/org/openmicroscopy/shoola/util/roi/model/util/Coord3D.java

adjust shift logic

---

src/main/java/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java
src/main/java/org/openmicroscopy/shoola/agents/treeviewer/view/TreeViewerComponent.java
src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java
src/main/java/org/openmicroscopy/shoola/env/data/OmeroDataService.java
src/main/java/org/openmicroscopy/shoola/env/data/OmeroDataServiceImpl.java
src/main/java/org/openmicroscopy/shoola/env/data/model/DownloadArchivedActivityParam.java
src/main/java/org/openmicroscopy/shoola/env/data/views/MetadataHandlerView.java
src/main/java/org/openmicroscopy/shoola/env/data/views/MetadataHandlerViewImpl.java
src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ArchivedImageLoader.java
src/main/java/org/openmicroscopy/shoola/env/ui/ArchivedLoader.java
src/main/java/org/openmicroscopy/shoola/env/ui/DownloadArchivedActivity.java
src/main/java/org/openmicroscopy/shoola/env/ui/OpenObjectLoader.java
src/test/java/org/openmicroscopy/shoola/env/data/NullOmeroPojoService.java

Use the download method from the Java gateway. On that occassion I also removed some unnecessary code.
Note: Should be merged together with https://github.com/ome/omero-gateway-java/pull/85 in order to get the same behaviour as it is now.

Use Gateway method for downloading image

---

src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterModel.java
src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ArchivedImageLoader.java
src/main/java/org/openmicroscopy/shoola/env/data/views/calls/FileUploader.java
src/main/java/org/openmicroscopy/shoola/env/data/views/calls/ResultsSaver.java
src/test/java/org/openmicroscopy/shoola/util/file/TestIOUtil.java

2 tests are currently failing on Windows see https://github.com/ome/omero-insight/pull/416
with the error
```
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)
at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:492)
at java.nio.file.Files.createDirectory(Files.java:674)
at java.nio.file.TempFileHelper.create(TempFileHelper.java:136)
at java.nio.file.TempFileHelper.createTempDirectory(TempFileHelper.java:173)
at java.nio.file.Files.createTempDirectory(Files.java:950)
at com.google.common.io.TempFileCreator$JavaNioCreator.createTempDir(TempFileCreator.java:102)
at com.google.common.io.Files.createTempDir(Files.java:439) …
```

Fix posix issue

---

src/main/java/org/openmicroscopy/shoola/env/data/ConnectionExceptionHandler.java
src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java
src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java
src/main/java/org/openmicroscopy/shoola/env/ui/TaskBarView.java

Fix https://github.com/ome/omero-insight/issues/424 . Now a error dialog will pop up telling the user that the server ran out of disk space.
Also fixes https://github.com/ome/omero-insight/issues/426 (thanks @scuniff )

Handle out of space

---

CHANGELOG.md
build.gradle

* Bump dependencies
* Add changelog

Prep 5.8.4

---

src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java

This PR fixes the URL when submitting to QA. The bug was introduced in https://github.com/ome/omero-insight/pull/327
The problem was noticed by @pwalczysko when testing the new QA
This prevents the user from submitting a file when an error happens
This might have an impact for the GS QA

fix endpoint

---

.github/workflows/gradle.yml

This is trying to address https://github.com/ome/omero-insight/issues/447
This branch starts from the https://github.com/ome/omero-insight/actions/runs/10884718399 - the commit a3ea82d1e59e2630ca3995ee9776a292f74e12ea -> where the build started to fail because of the same-named artifacts.
The strategy taken:
Upload:
1. add the ``matrix.os`` motif to the artifact name -> this is by itself not enough, as we build 2 artifacts per OS on 2 occassions
2. add a hardcoded string such as ``omero_`` which is taken from the foldername of the ``path`` variable just below the ``name`` of the artifact
Download:
1. adjust the ``file: artifacts/*`` -> ``file: artifacts*/*`` so that the artifacts are found in all folders created during Upload.
I have pushed an xxx-test8 tag to my [private branch …

Adjust the upload and download of artifacts v4
