ome/omero-insight

- src/main/java/org/openmicroscopy/shoola/util/ui/filechooser/GenericFileChooser.java
To test:
* Select a symlink and check that it works (mac, linux)
* Not possible to import on Windows
> Remove usage of ShellFolder

- README.md
The two sentences looked as if they needed connecting somehow.
> Adjust sentence about unpacking the artifact.

- build.gradle
see: https://github.com/ome/omero-java-gateway/pull/8
> Drop -java from omero-java-gateway

- build.gradle
Trivial whitespace fix, see diff.
> straighten indent

- build.gradle
- buildSrc/build.gradle
use release versions
Check that it is green
> use release versions

- LICENSE.txt
- README.md
Added requirements and instructions to setup a Windows environment manually (without a package manager).
> Added deploy instructions to readme for Windows

- CHANGELOG.md
add new entry originally in history.rst
> pre-release changelog

- src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java
replace usage of deprecated misspelled method
cc @dominikl
> replace usage of deprecated misspelled method

- src/main/java/org/openmicroscopy/shoola/agents/metadata/editor/PropertiesUI.java
handle null value
This was noticed on some images locally. The value returned was ``null``, this implies that the imported was constantly changing.
> handle null value

- build.gradle
- buildSrc/build.gradle
- buildSrc/src/main/groovy/org/openmicroscopy/PackagerPlugin.groovy
Updates insight to use latest 5.5.1 javapackager plugin.
Adds Windows start menu group.
> Utlises jpackager plugin 5.5.1 and adds windows start menu group

- src/main/java/org/openmicroscopy/shoola/env/data/DataServicesFactory.java
Insight was no longer registered
* If you use ``gradle run`` an entry with ``Unknown`` for the version will be added, otherwise it will be ``5.5.2-SNAPSHOT`` 
To test:
* Connect to merge-ci server
* Check that insight is registered
* Go to ``omero-web-prod``
* check the ``upgrade access`` log
cc @sbesson
> register insight

- build.gradle
In concert with the upcoming OMERO.server 5.5.1
> Bump gateway to 5.5.2

- src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java
- src/main/java/org/openmicroscopy/shoola/env/data/util/Status.java
- src/main/java/org/openmicroscopy/shoola/env/data/util/StatusLabel.java
indicate failure when connection issue
To test: 
* log in as a group owner
* try to import for another user
* the import will fail
* Check that a message "failed to upload" is displayed and that you can view the exception
cc @pwalczysko
> Import failure

- buildSrc/src/main/groovy/org/openmicroscopy/DistributePlugin.groovy
- buildSrc/src/main/groovy/org/openmicroscopy/InsightBasePlugin.groovy
- buildSrc/src/main/groovy/org/openmicroscopy/Utils.groovy
Fixes a class path for the imagej plugin distribution.
- test with imagej
See https://github.com/ome/omero-insight/issues/64
> class path fix for imagej plugin

- CHANGELOG.md
Add entries for 5.5.4
cc @pwalczysko @dominikl
> changelog 5.5.4

- src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java
Cast ByteBuffer to Byte for JDK8 support
cc @pwalczysko
>  ByteBuffer to Byte JDK8 support

- src/config/container.xml
bump link to latest BF version
cc @pwalczysko 
To check the link
* Install the insight-imageJ plugin into the plugins directory of ImageJ
* Check that you do not have bio-formats jar or loci jar in the plugins directory
* Try to connect to OMERO
* A dialog will pop up indicating that the dependencies are not installed. 
* Check the link
> Update link to BF

- src/main/java/org/openmicroscopy/shoola/env/log/LoggerFactory.java
Fix issue #91 
cc @pwalczysko @dominikl
> logback file

- .travis.yml
- README.md
- build.gradle
- buildSrc/src/main/groovy/org/openmicroscopy/PackagerPlugin.groovy
- src/test/java/org/openmicroscopy/shoola/util/file/TestIOUtil.java
This allows to build the windows executable in travis
We can now build both .exe and msi via travis
Note that installing Wix directly with chocolatey does not work (dotnet3.5 failure)
Edit: test failure on windows is fixed and re-activated
cc @pwalczysko @dominikl
> Build windows executable via travis

- build.gradle
> dependencies bump

- CHANGELOG.md
Prepare changelog for 5.5.10
cc @dominikl
> add entry for 5.5.10

- src/main/java/org/openmicroscopy/shoola/env/data/model/ImportableFile.java
Handle the case when the dataset is not set.
See https://www.openmicroscopy.org/qa2/qa/feedback/29385/
> handle case with no dataset

- src/main/java/org/openmicroscopy/shoola/env/data/AdminServiceImpl.java
- src/main/java/org/openmicroscopy/shoola/env/data/OMEROGateway.java
Fixes https://github.com/ome/omero-insight/issues/79
> Fix potential NPE

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/util/MapAnnotationObject.java
- src/main/java/org/openmicroscopy/shoola/env/data/model/ImportableObject.java
fix bug in MapAnnotationObject
> fix bug in MapAnnotationObject

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/MDEHelper.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/MetaDataDialog.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/util/ExportDialog.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/util/inout/ExportAsCsv.java
add feature export of metadata as key-values to csv file;
restructure bottom menu: group the export and template functionality as popup menu;
> MDE: add feature export to csv

- build.gradle
- src/main/java/org/openmicroscopy/shoola/env/ui/TaskBarManager.java
Remove string from log
see https://github.com/ome/omero-blitz/pull/93 for testing instructions
cc @dominikl @mtbc
> remove string from log

- CHANGELOG.md
Add entries for new release 
cc @dominikl
> Changelog 5.5.12

- CHANGELOG.md
Just add changelog entry for https://github.com/ome/omero-insight/pull/156 .
/cc @joshmoore
> Update changelog for 5.5.13 release

- src/main/java/org/openmicroscopy/shoola/env/ui/UserNotifierImpl.java
This PR fixes  a problem reported via qa system https://www.openmicroscopy.org/qa2/qa/feedback/29532/
cc @dominikl
> handle null folder

- CHANGELOG.md
- build.gradle
> Prepare Insight for 5.5.14 release.

- .github/workflows/main.yml
- src/test/java/org/openmicroscopy/shoola/util/file/TestIOUtil.java
Build and run the tests on 3 os using GH actions
cc @sbesson
> Actions to build on 3 os

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/util/TemplateDialog.java
disable load filter button if no template file is selected
> QA 29728: fix 

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/MetaDataDialog.java
- src/main/java/org/openmicroscopy/shoola/env/Environment.java
use correct LookupName for mde path
> MDE: fix use correct LookupName for mde path

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/util/TagData.java
create textfield if given type for inputField is unknown
> MDE: fix unknown inputField type

- src/config/mdeConfiguration.xml
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/MDEContent.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/MetaDataDialog.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/components/ModuleContent.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/components/ModuleController.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/components/ModuleTreeElement.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/components/submodules/converter/XMLWriter.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/components/view/ModuleContentGUI.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/components/view/TagDataTableModel.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/configuration/Editor_TagDataProp.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/util/TagData.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/util/TagDataProp.java
- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/util/inout/TagDataParser.java
If the "Show only required" check box is selected, only the content of objects that contain required tags will be displayed.
> MDE: Feat filter required

- src/main/java/org/openmicroscopy/shoola/agents/dataBrowser/view/SearchResultTable.java
- src/main/java/org/openmicroscopy/shoola/agents/dataBrowser/view/SearchResultTableModel.java
Convert the Date column to String in the search result table. Fixes https://github.com/ome/omero-insight/issues/178 .
**Test**:
Instructions for replicating the bug see issue.
> Convert Date to String

- .github/workflows/gradle.yml
> use gradle 6

- src/main/java/org/openmicroscopy/shoola/env/data/model/FileObject.java
To test:
* Open an image stored in OMERO
* Crop the image
* Import the image. Do not save it locally first
* Check that it works on Windows and Mac
cc @pwalczysko
> Fiji: import image not saved on disk: windows

- build.gradle
- buildSrc/build.gradle
- settings.gradle
see https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/
> use mavenCentral

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/components/view/ModuleTree.java
trigger the mouse event for object tree also under linux
> trigger the mouse event linux

- src/config/mdeConfiguration.xml
correction of mdeConfiguration.xml example for required field in setup "Example Setup: Fields"
> correction of mdeConfiguration.xml example for required field 

- .github/workflows/gradle.yml
- buildSrc/src/main/groovy/org/openmicroscopy/DistributePlugin.groovy
This PR tests the build in GHA with Gradle 6.8.3
The changes should work with Gradle 7. 
The failure happened when running ``gradle wrapper --gradle-version=6.8.3``
cc @dominikl
> Gradle7 fix

- build.gradle
Use the latest gateway version
> bump gateway version

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElement.java
Handle case when there is no components
see https://www.openmicroscopy.org/qa2/qa/feedback/30324/
> Fix NPE when components is null

- src/config/container.xml
- src/config/containerImporter.xml
See title. Fixes https://github.com/ome/omero-insight/issues/243 .
> Point to image.sc forum

- src/config/container.xml
- src/config/containerImporter.xml
Follow up to #244 . Point to `omero-insight` forum tag. 
/cc @sbesson .
> Point to forum, tag Insight

- src/config/container.xml
> remove loci_tools

- src/main/java/org/openmicroscopy/shoola/agents/treeviewer/RefreshExperimenterDataLoader.java
Fix https://www.openmicroscopy.org/qa2/qa/feedback/30781/
cc @dominikl
> fix NPE if no user is displayed

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElement.java
Fix for https://www.openmicroscopy.org/qa2/qa/feedback/30778/ 
cc @dominikl
> handle possible null object

- FAQ.md
Adds documentation for adjusting the JVM Options on Windows.
> Update FAQ.md JVM Options for Windows.

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/util/ExportDialog.java
see https://github.com/ome/omero-insight/issues/277
> Catching non-valid filehandle

- src/main/java/org/openmicroscopy/shoola/agents/imviewer/util/saver/ImgSaver.java
handle case when the main image does not exist e.g. cannot be loaded
> Bug: No image to save

- src/main/java/org/openmicroscopy/shoola/agents/metadata/editor/UserProfile.java
To reproduce the issue, use a user only in the system group
> Bug: NPE if user only in system group

- src/main/java/org/openmicroscopy/shoola/util/ui/ClosableTabbedPaneUI.java
With an error reported via https://www.openmicroscopy.org/qa2/qa/feedback/31082/
Code review is enough
> handle case without tab

- docs/conf.py
See https://github.com/ome/bio-formats-documentation/pull/250 for background
> Update extlinks to comply with Sphinx 5 deprecation warnings

- CHANGELOG.md
> Changelog for 5.7.2

- buildSrc/src/main/groovy/org/openmicroscopy/InsightBasePlugin.groovy
See title. Should fix https://github.com/ome/omero-insight/issues/316 .
> Increase max heap for insight to 4gb

- FAQ.md
This is a follow-up from changes in #317
> Memory FAQ

- CHANGELOG.md
- build.gradle
* Add changelog for 5.8.0
* Bump gateway version to 5.7.0
> Bump version and add changelog

- .github/workflows/gradle.yml
> upgrade set-up action. Current version uses set-output

- src/main/java/org/openmicroscopy/shoola/agents/metadata/editor/EditorModel.java
- src/main/java/org/openmicroscopy/shoola/agents/metadata/editor/UserProfile.java
Fixes https://github.com/ome/omero-insight/issues/324 . Another one of these where I'm not sure how to replicate the issue. But the additional null checks should prevent the NPE.
> Issue 324, NPE: UserProfile

- build.gradle
> bump org.openmicroscopy:omero-gateway to 5.8.1

- src/main/java/org/openmicroscopy/shoola/agents/imviewer/util/saver/ImgSaver.java
Replace special character by underscore in the name to avoid exception on Windows
see #/347
> replace : by _ in name on Windows

- src/main/java/org/openmicroscopy/shoola/agents/imviewer/util/proj/ProjSavingDialog.java
> handle case when no object is selected

- src/main/java/org/openmicroscopy/shoola/env/ui/DownloadActivity.java
This PR should handle the case when attempting to download files in root directory
see #358
> Handle root directory

- src/main/java/org/openmicroscopy/shoola/env/ui/TaskBarManager.java
adjust title in ij window: title is used to set image name
See https://github.com/ome/omero-insight/issues/362 for testing info
> adjust title in ImageJ/Fiji window

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElement.java
> handle case when project is not found

- src/main/java/org/openmicroscopy/shoola/agents/metadata/LDAPLoader.java
handle case when no LDAP info can be found
Do not crash when info not found
> LDAP check

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/view/ImporterUIElementLight.java
Code review
This should avoid https://github.com/ome/omero-insight/issues/364
> display failure dialog if any

- src/main/java/org/openmicroscopy/shoola/agents/treeviewer/RefreshExperimenterDataLoader.java
- src/main/java/org/openmicroscopy/shoola/agents/treeviewer/cmd/RefreshVisitor.java
Pass the node and not the Data object see #380
Check that you can refresh.
> Pass the node and not the Data object

- .readthedocs.yml
Update config ``build.os`` is now required
> update readthedocs config file

- build.gradle
bump org.openmicroscopy:omero-gateway to 5.8.2
> bump org.openmicroscopy:omero-gateway to 5.8.2

- src/main/java/org/openmicroscopy/shoola/util/roi/io/InputStrategy.java
> add missing return

- src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/components/ModuleList.java
> use super to remove the key from the HashMap

- src/main/java/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerControl.java
- src/main/java/org/openmicroscopy/shoola/agents/metadata/editor/EditorComponent.java
- src/main/java/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserControl.java
Fixes issues:
https://github.com/ome/omero-insight/issues/414
https://github.com/ome/omero-insight/issues/415
https://github.com/ome/omero-insight/issues/417
> Fix issues

- src/main/java/org/openmicroscopy/shoola/util/math/geom2D/PlanePoint2D.java
> use correct type in equals

- src/main/java/org/openmicroscopy/shoola/agents/measurement/view/ServerROITable.java
> handle case where ROI is not longer in table

- build.gradle
Bump Java gateway version to latest release. And also set Java to version 11.
> Bump gateway

- CHANGELOG.md
See title.
The PRs still need to be merged.
> Add changelog for upcoming 5.8.5 release
